import React, { useState, useContext, useEffect } from 'react';
import { useNavigate, useLocation, Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Leaf, Award, BarChart3, ShieldCheck, Mail, Lock, User, 
  ArrowRight, ChevronRight, Check, Zap, Smartphone, 
  Target, Globe, BarChart, Sparkles, X, Menu
} from 'lucide-react';
import AuthContext from '../context/AuthContext';
import toast from 'react-hot-toast';

const Welcome = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isLogin, setIsLogin] = useState(true);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [formData, setFormData] = useState({
    username: '',
    email: '',
    password: '',
  });
  const [isLoading, setIsLoading] = useState(false);
  
  const { login, signup, token } = useContext(AuthContext);
  const navigate = useNavigate();
  const location = useLocation();

  useEffect(() => {
    if (token) navigate('/');
  }, [token, navigate]);

  const handleInputChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleAuthSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    try {
      if (isLogin) {
        await login(formData.email, formData.password);
        toast.success('Welcome back!');
      } else {
        await signup(formData.username, formData.email, formData.password);
        toast.success('Account created successfully!');
      }
      navigate('/');
    } catch (err) {
      toast.error(err.response?.data?.message || `Failed to ${isLogin ? 'login' : 'sign up'}`);
    } finally {
      setIsLoading(false);
    }
  };

  const features = [
    { 
      icon: <Target className="w-6 h-6 text-green-600" />, 
      title: 'Smart Carbon Tracking', 
      description: 'Automatically breakdown your footprint by transport, food, and energy consumption.' 
    },
    { 
      icon: <Sparkles className="w-6 h-6 text-green-600" />, 
      title: 'AI Recommendations', 
      description: 'Get personalized, actionable tips generated by AI to reduce your specific emissions.' 
    },
    { 
      icon: <BarChart className="w-6 h-6 text-green-600" />, 
      title: 'Visual Analytics', 
      description: 'Beautiful, real-time charts and reports to monitor your environmental progress.' 
    },
    { 
      icon: <Zap className="w-6 h-6 text-green-600" />, 
      title: 'Progress Tracking', 
      description: 'Receive insights into your daily and weekly improvements as you go green.' 
    },
  ];

  const steps = [
    { icon: <User className="w-6 h-6" />, title: 'Sign Up', desc: 'Create your secure account in seconds.' },
    { icon: <Smartphone className="w-6 h-6" />, title: 'Enter Data', desc: 'Add details about your daily lifestyle.' },
    { icon: <Globe className="w-6 h-6" />, title: 'Get Insights', desc: 'Receive real-time tips to reduce emissions.' },
  ];

  const pricing = [
    { 
      name: 'Free', 
      price: '$0', 
      features: ['Basic activity tracking', 'Weekly email report', 'Community access', 'Standard analytics'],
      cta: 'Get Started',
      popular: false 
    },
    { 
      name: 'Pro', 
      price: '$12', 
      features: ['Advanced AI insights', 'Real-time sensor sync', 'Priority support', 'Detailed PDF reports', 'Custom dashboards'],
      cta: 'Try Pro Free',
      popular: true 
    },
  ];

  return (
    <div className="min-h-screen bg-white">
      {/* Navbar */}
      <nav className="fixed top-0 w-full z-50 bg-white/80 backdrop-blur-md border-b border-slate-100">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-2 bg-green-500 rounded-lg text-white">
              <Leaf className="w-6 h-6" />
            </div>
            <span className="text-xl font-bold tracking-tight text-slate-900">EcoTrack</span>
          </div>
          
          {/* Desktop Nav */}
          <div className="hidden md:flex items-center gap-8">
            <a href="#features" className="text-sm font-medium text-slate-600 hover:text-green-600 transition-colors">Features</a>
            <a href="#how-it-works" className="text-sm font-medium text-slate-600 hover:text-green-600 transition-colors">How it Works</a>
            <a href="#pricing" className="text-sm font-medium text-slate-600 hover:text-green-600 transition-colors">Pricing</a>
            <button 
              onClick={() => { setIsLogin(true); setIsModalOpen(true); }}
              className="text-sm font-medium text-slate-900 hover:text-green-600 transition-colors"
            >
              Sign In
            </button>
            <button 
              onClick={() => { setIsLogin(false); setIsModalOpen(true); }}
              className="btn-primary py-2 px-5"
            >
              Get Started
            </button>
          </div>

          {/* Mobile Menu Toggle */}
          <button className="md:hidden p-2 text-slate-600" onClick={() => setIsMenuOpen(!isMenuOpen)}>
            {isMenuOpen ? <X /> : <Menu />}
          </button>
        </div>

        {/* Mobile Menu */}
        <AnimatePresence>
          {isMenuOpen && (
            <motion.div 
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="md:hidden bg-white border-b border-slate-100 overflow-hidden"
            >
              <div className="flex flex-col p-6 gap-4">
                <a href="#features" onClick={() => setIsMenuOpen(false)} className="font-medium text-slate-600">Features</a>
                <a href="#how-it-works" onClick={() => setIsMenuOpen(false)} className="font-medium text-slate-600">How it Works</a>
                <a href="#pricing" onClick={() => setIsMenuOpen(false)} className="font-medium text-slate-600">Pricing</a>
                <hr className="border-slate-100" />
                <button 
                  onClick={() => { setIsMenuOpen(false); setIsLogin(true); setIsModalOpen(true); }}
                  className="font-medium text-slate-900 text-left"
                >
                  Sign In
                </button>
                <button 
                  onClick={() => { setIsMenuOpen(false); setIsLogin(false); setIsModalOpen(true); }}
                  className="btn-primary w-full"
                >
                  Get Started
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </nav>

      {/* Hero Section */}
      <section className="pt-40 pb-20 px-6">
        <div className="max-w-7xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <span className="px-4 py-1.5 bg-green-50 text-green-700 text-xs font-bold uppercase tracking-widest rounded-full mb-6 inline-block">
              Earth Day 2024 Release
            </span>
            <h1 className="text-5xl md:text-7xl font-black text-slate-900 mb-8 tracking-tighter leading-[1.1]">
              Track and Reduce Your <br />
              Carbon Footprint <span className="text-green-500">Effortlessly</span>
            </h1>
            <p className="text-xl text-slate-600 max-w-2xl mx-auto mb-10 leading-relaxed">
              Get real-time insights and AI-powered recommendations to live sustainably. Join thousands making a difference today.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <button 
                onClick={() => { setIsLogin(false); setIsModalOpen(true); }}
                className="btn-primary px-8 py-4 text-lg w-full sm:w-auto"
              >
                Get Started Free
              </button>
              <button className="btn-secondary px-8 py-4 text-lg w-full sm:w-auto flex items-center justify-center gap-2">
                View Live Demo <ChevronRight size={18} />
              </button>
            </div>
          </motion.div>

          {/* Dashboard Preview */}
          <motion.div 
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.8, delay: 0.3 }}
            className="mt-20 relative max-w-5xl mx-auto"
          >
            <div className="absolute inset-0 bg-green-500/10 blur-[100px] rounded-full"></div>
            <div className="bg-white border border-slate-200 rounded-2xl shadow-2xl overflow-hidden p-2">
               <img src="/dashboard_preview.png" alt="Ecoflow Dashboard" className="rounded-xl w-full border border-slate-100 shadow-inner" />
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-24 bg-slate-50 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">Precision Tracking, Better Impact</h2>
            <p className="text-slate-600">Powerful features designed to help you understand and shrink your footprint.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, i) => (
              <div key={i} className="saas-card p-8 bg-white">
                <div className="w-12 h-12 bg-green-50 rounded-xl flex items-center justify-center mb-6">
                  {feature.icon}
                </div>
                <h3 className="text-xl font-bold text-slate-900 mb-3">{feature.title}</h3>
                <p className="text-slate-500 text-sm leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it Works */}
      <section id="how-it-works" className="py-24 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">Start your journey in 3 steps</h2>
          </div>
          <div className="flex flex-col md:flex-row gap-12 items-center justify-between">
            {steps.map((step, i) => (
              <div key={i} className="flex-1 flex flex-col items-center text-center group">
                <div className="w-16 h-16 bg-slate-900 text-white rounded-2xl flex items-center justify-center mb-6 group-hover:bg-green-500 transition-colors duration-500">
                  {step.icon}
                </div>
                <h3 className="text-xl font-bold mb-2">{step.title}</h3>
                <p className="text-slate-500">{step.desc}</p>
                {i < 2 && <div className="hidden lg:block w-32 h-[1px] bg-slate-200 mt-10"></div>}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-24 bg-slate-900 text-white px-6">
        <div className="max-w-7xl mx-auto text-center">
          <h2 className="text-3xl font-bold mb-4 tracking-tight">Flexible Plans for Everyone</h2>
          <p className="text-slate-400 mb-16">Join EcoTrack today and start making a difference.</p>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            {pricing.map((plan, i) => (
              <div 
                key={i} 
                className={`p-10 rounded-3xl text-left flex flex-col border ${plan.popular ? 'border-green-500 bg-white/5 ring-1 ring-green-500' : 'border-slate-800'}`}
              >
                <div className="flex justify-between items-center mb-4">
                  <h3 className="text-xl font-bold">{plan.name}</h3>
                  {plan.popular && <span className="bg-green-500 text-xs font-black px-3 py-1 rounded-full uppercase">Most Popular</span>}
                </div>
                <div className="flex items-baseline gap-1 mb-8">
                  <span className="text-4xl font-black">{plan.price}</span>
                  <span className="text-slate-400 text-sm">/per month</span>
                </div>
                <ul className="space-y-4 mb-10 flex-1">
                  {plan.features.map((f, j) => (
                    <li key={j} className="flex items-center gap-3 text-sm text-slate-300">
                      <Check className="w-4 h-4 text-green-500" /> {f}
                    </li>
                  ))}
                </ul>
                <button 
                   onClick={() => { setIsLogin(false); setIsModalOpen(true); }}
                   className={`w-full py-4 rounded-xl font-bold transition-all ${plan.popular ? 'bg-green-500 text-white hover:bg-green-600' : 'bg-white text-slate-900 hover:bg-slate-100'}`}
                >
                  {plan.cta}
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-20 border-t border-slate-100">
        <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-4 gap-12">
          <div className="md:col-span-2">
            <div className="flex items-center gap-2 mb-6">
              <div className="p-2 bg-green-500 rounded-lg text-white">
                <Leaf className="w-6 h-6" />
              </div>
              <span className="text-xl font-bold tracking-tight text-slate-900">EcoTrack</span>
            </div>
            <p className="text-slate-500 max-w-sm mb-8 leading-relaxed">
              Empowering individuals and teams to track, understand, and offset their carbon footprint with modern precision tools and community insights.
            </p>
            <div className="flex gap-4">
               {/* Social placeholders */}
               {[Globe, Smartphone, Mail].map((Icon, i) => (
                 <a key={i} href="#" className="p-2 text-slate-400 hover:text-green-600 transition-colors bg-slate-50 rounded-lg">
                   <Icon size={20} />
                 </a>
               ))}
            </div>
          </div>
          <div>
            <h4 className="font-bold mb-6">Product</h4>
            <ul className="space-y-4 text-slate-500 text-sm">
              <li><a href="#" className="hover:text-green-600">Analytics</a></li>
              <li><a href="#" className="hover:text-green-600">Pricing</a></li>
              <li><a href="#" className="hover:text-green-600">Enterprise</a></li>
              <li><a href="#" className="hover:text-green-600">Resources</a></li>
            </ul>
          </div>
          <div>
            <h4 className="font-bold mb-6">Company</h4>
            <ul className="space-y-4 text-slate-500 text-sm">
              <li><Link to="/about" className="hover:text-green-600">About</Link></li>
              <li><a href="https://github.com" className="hover:text-green-600">GitHub</a></li>
              <li><a href="#" className="hover:text-green-600">Careers</a></li>
              <li><a href="#" className="hover:text-green-600">Contact</a></li>
            </ul>
          </div>
        </div>
        <div className="max-w-7xl mx-auto px-6 mt-20 pt-8 border-t border-slate-100 flex flex-col md:flex-row justify-between items-center gap-4 text-xs text-slate-400 uppercase tracking-widest font-bold">
           <p>© 2024 EcoTrack Sustainability Systems Inc.</p>
           <div className="flex gap-8">
              <a href="#" className="hover:text-slate-900">Privacy Policy</a>
              <a href="#" className="hover:text-slate-900">Terms of Service</a>
           </div>
        </div>
      </footer>

      {/* Auth Modal */}
      <AnimatePresence>
        {isModalOpen && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center p-6">
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm"
              onClick={() => setIsModalOpen(false)}
            />
            <motion.div 
              initial={{ opacity: 0, scale: 0.9, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 20 }}
              className="relative bg-white rounded-3xl shadow-2xl w-full max-w-md p-10 overflow-hidden"
            >
              <button 
                onClick={() => setIsModalOpen(false)}
                className="absolute top-6 right-6 p-2 text-slate-400 hover:text-slate-900"
              >
                <X size={20} />
              </button>

              <div className="text-center mb-10">
                <h2 className="text-3xl font-black text-slate-900 mb-2">
                  {isLogin ? 'Welcome Back' : 'Get Started'}
                </h2>
                <p className="text-slate-500 text-sm">
                  {isLogin ? 'Sign in to continue tracking impact' : 'Start your sustainability journey today'}
                </p>
              </div>

              <form onSubmit={handleAuthSubmit} className="space-y-5">
                {!isLogin && (
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-2">Full Name</label>
                    <div className="relative">
                      <User className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 w-4 h-4" />
                      <input 
                        type="text" 
                        name="username"
                        required
                        className="w-full pl-11 pr-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-green-500 outline-none transition-all"
                        placeholder="John Doe"
                        value={formData.username}
                        onChange={handleInputChange}
                      />
                    </div>
                  </div>
                )}
                <div>
                  <label className="block text-sm font-bold text-slate-700 mb-2">Email Address</label>
                  <div className="relative">
                    <Mail className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 w-4 h-4" />
                    <input 
                      type="email" 
                      name="email"
                      required
                      className="w-full pl-11 pr-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-green-500 outline-none transition-all"
                      placeholder="you@example.com"
                      value={formData.email}
                      onChange={handleInputChange}
                    />
                  </div>
                </div>
                <div>
                  <label className="block text-sm font-bold text-slate-700 mb-2">Password</label>
                  <div className="relative">
                    <Lock className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 w-4 h-4" />
                    <input 
                      type="password" 
                      name="password"
                      required
                      className="w-full pl-11 pr-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-green-500 outline-none transition-all"
                      placeholder="••••••••"
                      value={formData.password}
                      onChange={handleInputChange}
                    />
                  </div>
                </div>
                <button 
                  type="submit" 
                  disabled={isLoading}
                  className="btn-primary w-full py-4 mt-4 flex items-center justify-center gap-3"
                >
                  {isLoading ? <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> : (isLogin ? 'Sign In' : 'Create Account')}
                </button>
              </form>

              <div className="mt-8 text-center pt-8 border-t border-slate-100 flex items-center justify-center gap-2 text-sm">
                <span className="text-slate-500">
                  {isLogin ? "Don't have an account?" : "Already have an account?"}
                </span>
                <button 
                  onClick={() => setIsLogin(!isLogin)}
                  className="font-bold text-green-600 hover:text-green-700 underline underline-offset-4"
                >
                  {isLogin ? 'Sign Up' : 'Log In'}
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default Welcome;
